export const ADVISORY_CATEGORIES = [
  'Phishing & Messaging',
  'Identity & Access',
  'Financial Fraud',
  'Malware & Device Security',
  'Social Engineering',
  'Data & Privacy',
  'Cybersecurity Awareness'
]

export const ADVISORY_RESPONSE_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    title: {
      type: 'string',
      description: 'Clear advisory title, ideally under 55 characters.'
    },
    intro: {
      type: 'string',
      description: 'Two or three concise sentences explaining the risk in plain UK English.'
    },
    category: {
      type: 'string',
      enum: ADVISORY_CATEGORIES
    },
    sectionOneTitle: {
      type: 'string',
      description: 'Short heading such as How It Works, How the Scam Works or Key Risks.'
    },
    sectionOnePoints: {
      type: 'array',
      minItems: 4,
      maxItems: 4,
      items: {
        type: 'string',
        description: 'One concise explanatory point.'
      }
    },
    sectionTwoTitle: {
      type: 'string',
      description: 'Short action-focused heading such as Best Practices or How to Stay Safe.'
    },
    sectionTwoPoints: {
      type: 'array',
      minItems: 4,
      maxItems: 4,
      items: {
        type: 'string',
        description: 'One concise practical safety action.'
      }
    }
  },
  required: [
    'title',
    'intro',
    'category',
    'sectionOneTitle',
    'sectionOnePoints',
    'sectionTwoTitle',
    'sectionTwoPoints'
  ]
}

const AUDIENCE_GUIDANCE = {
  'All Employees': 'Use plain language suitable for non-technical employees.',
  'Senior Executives': 'Use executive-relevant language focused on business risk, impersonation, approvals and sensitive information without addressing the reader as the CEO.',
  'Finance Teams': 'Emphasise payment verification, approval controls and financial fraud indicators where relevant.',
  'IT & Security Teams': 'Allow slightly more technical language but keep the advisory concise and awareness-focused.',
  Customers: 'Use customer-friendly language and avoid internal process references unless the user supplied them.'
}

export function buildAdvisoryPrompt({ topic, audience, advisoryType }) {
  const audienceInstruction = AUDIENCE_GUIDANCE[audience] || AUDIENCE_GUIDANCE['All Employees']

  return `Create one polished cybersecurity awareness advisory about: "${topic}".

Audience: ${audience}
Advisory type: ${advisoryType}

Writing requirements:
- Use UK English.
- Write for awareness, not for a technical incident-response manual.
- Keep the title concise and natural. Do not use clickbait wording.
- The introduction must be 2 to 3 short sentences and should normally fit within about 230 characters.
- Return exactly 4 points in the first section and exactly 4 points in the second section.
- Keep all points similar in visual length. Aim for roughly 70 to 125 characters per point.
- Use simple words where possible.
- Avoid unnecessary jargon and filler.
- Avoid a comma before "and" or "or" in a simple list.
- Do not repeat the same advice in different words.
- Do not invent organisation-specific reporting addresses, policies, product names or facts.
- Make each safety point actionable.
- ${audienceInstruction}

Content structure guidance:
- First section: explain how the threat works, the key risks or the attack progression.
- Second section: practical best practices or actions the audience should take.
- Choose the closest category from the allowed schema.
- The result must stand alone as an advisory and must not mention that it was generated by AI.`
}
