export default function GeneratedAdvisoryView({ result, loading, error, onRegenerate, onUseClassic }) {
  if (loading) {
    return (
      <div className="ai-advisory-stage loading">
        <div className="ai-loader" />
        <strong>Creating a new advisory from the approved reference style…</strong>
        <span>Writing copy → choosing reference → generating complete artwork</span>
      </div>
    )
  }

  if (!result) {
    return (
      <div className="ai-advisory-stage empty">
        <div className="ai-stage-icon">AI</div>
        <strong>Reference-guided AI advisory</strong>
        <span>Enter a topic and generate a fresh advisory image inspired by the approved GitHub reference library.</span>
        {error && <p className="ai-stage-error">{error}</p>}
      </div>
    )
  }

  return (
    <div className="ai-result-shell">
      <div className="ai-result-image-wrap">
        <img className="ai-result-image" src={result.imageUrl} alt={`${result.advisory?.title || 'Generated'} advisory`} />
      </div>
      <div className="ai-result-meta">
        <div><span>Generated by</span><strong>Replicate · FLUX Kontext Pro</strong></div>
        <div><span>Reference</span><strong>{result.reference?.title}</strong></div>
        <div><span>Similarity</span><strong>{result.similarity}</strong></div>
        <div><span>Concept</span><strong>{result.concept}</strong></div>
      </div>
      <div className="ai-result-actions">
        <button type="button" className="primary-button" onClick={onRegenerate}>Generate another concept</button>
        <a className="ghost-button ai-download-link" href={result.imageUrl} target="_blank" rel="noreferrer">Open full image</a>
        <button type="button" className="ghost-button" onClick={onUseClassic}>Open structured fallback</button>
      </div>
      {error && <p className="ai-stage-error">{error}</p>}
    </div>
  )
}
