import { useMemo, useRef, useState } from 'react'
import AdvisoryCanvas from './components/AdvisoryCanvas'
import { advisoryReferences } from './data/references'
import {
  ADVISORY_TYPES,
  AUDIENCES,
  TEMPLATES,
  generateAdvisory,
  getRecommendedTemplate
} from './lib/advisoryEngine'
import { exportAsPng, exportAsSvg } from './lib/exportAdvisory'

const initialAdvisory = generateAdvisory({
  topic: 'MFA Fatigue Attack',
  audience: 'All Employees',
  advisoryType: 'Internal Advisory'
})

function EditablePoint({ value, onChange, index }) {
  return (
    <label className="point-field">
      <span>{index + 1}</span>
      <textarea value={value} rows="3" onChange={event => onChange(event.target.value)} />
    </label>
  )
}

function App() {
  const canvasRef = useRef(null)
  const [topic, setTopic] = useState(initialAdvisory.topic)
  const [audience, setAudience] = useState(initialAdvisory.audience)
  const [advisoryType, setAdvisoryType] = useState(initialAdvisory.advisoryType)
  const [template, setTemplate] = useState(getRecommendedTemplate(initialAdvisory.category))
  const [advisory, setAdvisory] = useState(initialAdvisory)
  const [panel, setPanel] = useState('create')
  const [referenceSearch, setReferenceSearch] = useState('')

  const filteredReferences = useMemo(() => {
    const query = referenceSearch.trim().toLowerCase()
    if (!query) return advisoryReferences
    return advisoryReferences.filter(item => item.title.toLowerCase().includes(query))
  }, [referenceSearch])

  const updateField = (key, value) => {
    setAdvisory(current => ({ ...current, [key]: value }))
  }

  const updatePoint = (key, index, value) => {
    setAdvisory(current => ({
      ...current,
      [key]: current[key].map((point, pointIndex) => pointIndex === index ? value : point)
    }))
  }

  const handleGenerate = () => {
    const next = generateAdvisory({ topic, audience, advisoryType })
    setAdvisory(next)
    setTemplate(getRecommendedTemplate(next.category))
    setPanel('edit')
  }

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="brand-lockup">
          <div className="brand-mark">I</div>
          <div>
            <strong>Advisory Generator</strong>
            <span>Innvikta Design Studio</span>
          </div>
        </div>
        <div className="topbar-actions">
          <button className="ghost-button" type="button" onClick={() => exportAsSvg(canvasRef.current, advisory.title)}>Export SVG</button>
          <button className="primary-button" type="button" onClick={() => exportAsPng(canvasRef.current, advisory.title)}>Export PNG</button>
        </div>
      </header>

      <main className="workspace">
        <aside className="sidebar">
          <nav className="panel-tabs" aria-label="Editor panels">
            <button className={panel === 'create' ? 'active' : ''} onClick={() => setPanel('create')}>Create</button>
            <button className={panel === 'edit' ? 'active' : ''} onClick={() => setPanel('edit')}>Edit</button>
            <button className={panel === 'references' ? 'active' : ''} onClick={() => setPanel('references')}>References</button>
          </nav>

          {panel === 'create' && (
            <section className="panel-content">
              <div className="panel-heading">
                <span className="eyebrow">GENERATE</span>
                <h1>Create an advisory</h1>
                <p>Start with the topic. The engine structures the copy and selects an appropriate design composition.</p>
              </div>

              <label className="field">
                <span>Advisory topic</span>
                <input value={topic} onChange={event => setTopic(event.target.value)} placeholder="e.g. QR Code Phishing" />
              </label>

              <label className="field">
                <span>Audience</span>
                <select value={audience} onChange={event => setAudience(event.target.value)}>
                  {AUDIENCES.map(item => <option key={item}>{item}</option>)}
                </select>
              </label>

              <label className="field">
                <span>Advisory type</span>
                <select value={advisoryType} onChange={event => setAdvisoryType(event.target.value)}>
                  {ADVISORY_TYPES.map(item => <option key={item}>{item}</option>)}
                </select>
              </label>

              <button className="generate-button" type="button" onClick={handleGenerate} disabled={!topic.trim()}>
                <span>Generate advisory</span>
                <small>Structured copy + recommended layout</small>
              </button>

              <div className="system-note">
                <strong>Phase 1 engine</strong>
                <p>Copy is currently generated by controlled local rules. The same structured schema is ready for an AI API in the next phase.</p>
              </div>
            </section>
          )}

          {panel === 'edit' && (
            <section className="panel-content edit-panel">
              <div className="panel-heading compact">
                <span className="eyebrow">CONTENT</span>
                <h2>Edit advisory</h2>
                <p>Changes update the vector artwork immediately.</p>
              </div>

              <label className="field">
                <span>Title</span>
                <input value={advisory.title} onChange={event => updateField('title', event.target.value)} />
              </label>

              <label className="field">
                <span>Introduction</span>
                <textarea rows="5" value={advisory.intro} onChange={event => updateField('intro', event.target.value)} />
              </label>

              <div className="editor-group">
                <input className="section-title-input" value={advisory.sectionOneTitle} onChange={event => updateField('sectionOneTitle', event.target.value)} />
                {advisory.sectionOnePoints.map((point, index) => (
                  <EditablePoint key={`one-${index}`} index={index} value={point} onChange={value => updatePoint('sectionOnePoints', index, value)} />
                ))}
              </div>

              <div className="editor-group">
                <input className="section-title-input" value={advisory.sectionTwoTitle} onChange={event => updateField('sectionTwoTitle', event.target.value)} />
                {advisory.sectionTwoPoints.map((point, index) => (
                  <EditablePoint key={`two-${index}`} index={index} value={point} onChange={value => updatePoint('sectionTwoPoints', index, value)} />
                ))}
              </div>
            </section>
          )}

          {panel === 'references' && (
            <section className="panel-content reference-panel">
              <div className="panel-heading compact">
                <span className="eyebrow">DESIGN LIBRARY</span>
                <h2>Existing advisories</h2>
                <p>These uploaded designs are the visual reference set for the generator.</p>
              </div>
              <label className="field">
                <span>Search references</span>
                <input value={referenceSearch} onChange={event => setReferenceSearch(event.target.value)} placeholder="Search topic" />
              </label>
              <div className="reference-grid">
                {filteredReferences.map(reference => (
                  <a key={reference.id} className="reference-card" href={reference.url} target="_blank" rel="noreferrer">
                    <img src={reference.url} alt={reference.title} loading="lazy" />
                    <span>{reference.title}</span>
                  </a>
                ))}
              </div>
            </section>
          )}
        </aside>

        <section className="studio">
          <div className="studio-toolbar">
            <div>
              <span className="toolbar-label">Layout</span>
              <div className="template-switcher">
                {TEMPLATES.map(item => (
                  <button
                    key={item.id}
                    type="button"
                    className={template === item.id ? 'active' : ''}
                    onClick={() => setTemplate(item.id)}
                    title={item.description}
                  >
                    {item.name}
                  </button>
                ))}
              </div>
            </div>
            <div className="quality-chip">
              <span className="quality-dot" />
              Vector-safe layout
            </div>
          </div>

          <div className="canvas-stage">
            <div className="canvas-frame">
              <AdvisoryCanvas ref={canvasRef} advisory={advisory} template={template} />
            </div>
          </div>

          <div className="statusbar">
            <span>{advisory.category}</span>
            <span>1080 × 1350</span>
            <span>SVG master</span>
          </div>
        </section>
      </main>
    </div>
  )
}

export default App
